<?php
/**
 * Implements hook_theme().
 */
function landing_page_theme($existing, $type, $theme, $path) {
  $variables = [
    'landing_page' => [
      'variables' => [
        'page_title' => NULL,
        'subtitle' => NULL,
        'show_button' => false,
        'button_text' => NULL,
        'button_url' => NULL,
      ],
      'template' => 'landing_page',
    ],
  ];
  return $variables;
}

/**
 * Template preprocess function for the front page.
 *
 * @param array $variables
 *   An associative array containing:
 *   - source_text
 */
function template_preprocess_landing_page(&$variables) {

}
