landing_page.settings:
  type: config_object
  label: 'Front page settings'
  mapping:
    landing_page:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Front page title:'
        subtitle:
          type: text
          label: 'Subtitle for the front page:'
        show_button:
          type: boolean
          label: 'Show a button to link user\'s elsewhere?'
        button_text:
          type: text
          label: 'Button Text'
        button_url:
          type: link
          label: 'The URL for the button to point to:'
        # banner_image:
        #   type: image
        #   label: 'The image for the banner:'
