<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function tenant_victories_theme($existing, $type, $theme, $path) {
  return [
        'node__tenant_victory' => [
        'template' => 'node--tenant_victory',
        'base hook' => 'node',
        ],
        'views_view_fields__tenant_victories' => [
        'template' => 'views-view-fields--tenant_victories',
        'base hook' => 'node',
        ],
    ];
}

/**
* Implements hook_views_pre_render().
*/
function tenant_victories_views_pre_render(ViewExecutable $view) {
    if (isset($view) && ($view->storage->id() == 'tenant_victories')) {
        $view->element['#attached']['library'][] = 'tenant_victories/view_css';
    }
}
