tenant_resources.settings:
  type: config_object
  label: Tenant Resources Module Settings
  mapping:
    introduction:
      type: text
      label: The introductory text to display on the Tenant Resources page
